# Configuration for Rasa NLU.
language: de
pipeline: pretrained_embeddings_spacy

# Configuration for Rasa Core.
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy
  - name: FallbackPolicy
    nlu_threshold: 0.1
    core_threshold: 0.1
    fallback_action_name: 'action_default_fallback'
